apiVersion: v1
kind: ConfigMap
metadata:
  name: alertmanager-config
  namespace: observability-lab
data:
  alertmanager.yml: |
    global:
      resolve_timeout: 1m
    route:
      receiver: local-demo
      group_wait: 5s
      group_interval: 30s
      repeat_interval: 10m
    receivers:
      - name: local-demo
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
  namespace: observability-lab
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.28.0
          args: ["--config.file=/etc/alertmanager/alertmanager.yml"]
          ports:
            - containerPort: 9093
          volumeMounts:
            - name: config
              mountPath: /etc/alertmanager
      volumes:
        - name: config
          configMap:
            name: alertmanager-config
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
  namespace: observability-lab
spec:
  selector:
    app: alertmanager
  ports:
    - name: http
      port: 9093
      targetPort: 9093
