{
 "title": "Cloud-Native Observability Lab - Orders API",
 "tags": [
  "cloud-native",
  "observability",
  "demo"
 ],
 "time": { "from": "now-30m", "to": "now" },
 "refresh": "10s",
 "panels": [
  {
   "title": "Request rate",
   "type": "stat",
   "gridPos": { "x": 0, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(demo_http_requests_total[1m]))"
    }
   ]
  },
  {
   "title": "Error rate",
   "type": "stat",
   "gridPos": { "x": 6, "y": 0, "w": 6, "h": 4 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(rate(demo_http_requests_total{status=~\"5..\"}[1m])) / clamp_min(sum(rate(demo_http_requests_total[1m])), 0.001)"
    }
   ]
  },
  {
   "title": "p95 latency by route",
   "type": "timeseries",
   "gridPos": { "x": 12, "y": 0, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(demo_http_request_duration_seconds_bucket[2m])) by (le, route))",
     "legendFormat": "{{route}}"
    }
   ]
  },
  {
   "title": "Requests by route/status",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 4, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(demo_http_requests_total[1m])) by (route, status)",
     "legendFormat": "{{route}} {{status}}"
    }
   ]
  },
  {
   "title": "Redis dependency latency p95",
   "type": "timeseries",
   "gridPos": { "x": 0, "y": 12, "w": 12, "h": 8 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "targets": [
    {
     "expr": "histogram_quantile(0.95, sum(rate(demo_dependency_duration_seconds_bucket[2m])) by (le, operation))",
     "legendFormat": "redis {{operation}}"
    }
   ]
  },
  {
   "title": "Logs from Loki",
   "type": "logs",
   "gridPos": { "x": 12, "y": 8, "w": 12, "h": 12 },
   "targets": [
    {
     "expr": "{service_name=\"orders-api\"} | json"
    }
   ]
  },
  {
   "title": "Recent traces",
   "type": "table",
   "gridPos": { "x": 0, "y": 20, "w": 12, "h": 8 },
   "targets": [
    {
     "query": "{ resource.service.name = \"orders-api\" }"
    }
   ]
  },
  {
   "title": "Active alerts",
   "type": "table",
   "gridPos": { "x": 12, "y": 20, "w": 12, "h": 8 },
   "targets": [
    {
     "expr": "ALERTS{alertstate=\"firing\"}"
    }
   ]
  }
 ]
}